//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movselex.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Movselex.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   You you want to delete the {0}. Are you sure? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmMessageDelete {
            get {
                return ResourceManager.GetString("ConfirmMessageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It also deletes files. Are you sure? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmMessageFileDelete {
            get {
                return ResourceManager.GetString("ConfirmMessageFileDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete the file that has been registered in the group. is it OK? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmMessageGroupDelete {
            get {
                return ResourceManager.GetString("ConfirmMessageGroupDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It will move the {0} to {1}. Are you sure? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmMessageMove {
            get {
                return ResourceManager.GetString("ConfirmMessageMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It will release a group of {0}. Are you sure? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmMessageUnGroup {
            get {
                return ResourceManager.GetString("ConfirmMessageUnGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Group に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteGroup {
            get {
                return ResourceManager.GetString("DeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Group に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditGroup {
            get {
                return ResourceManager.GetString("EditGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Library に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditLibrary {
            get {
                return ResourceManager.GetString("EditLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grouping に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grouping {
            get {
                return ResourceManager.GetString("Grouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If not specified it will monitor the most registered a large number of directories in the database. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageAttentionMonitorDirectory {
            get {
                return ResourceManager.GetString("MessageAttentionMonitorDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit the group. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageEditGroup {
            get {
                return ResourceManager.GetString("MessageEditGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit the library. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageEditLibrary {
            get {
                return ResourceManager.GetString("MessageEditLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unknown error has occurred. It will exit the application. Please send the error log to the developer. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageFatalError {
            get {
                return ResourceManager.GetString("MessageFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please specify the location where you want to move. Move directly to the specified location. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageMoveFile {
            get {
                return ResourceManager.GetString("MessageMoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please specify the location where you want to move. Moves to create a folder in the group name in the specified location. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageMoveGroupDirectory {
            get {
                return ResourceManager.GetString("MessageMoveGroupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register the group. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageRegistGroup {
            get {
                return ResourceManager.GetString("MessageRegistGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The selected {0} item に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageSelectedItems {
            get {
                return ResourceManager.GetString("MessageSelectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please specify the MPC-HC.exe. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageSelectMpcExe {
            get {
                return ResourceManager.GetString("MessageSelectMpcExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unknown error has occurred. Please send the error log to the developer. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageUnknownError {
            get {
                return ResourceManager.GetString("MessageUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MoveFile {
            get {
                return ResourceManager.GetString("MoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move Group Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MoveGroupFiles {
            get {
                return ResourceManager.GetString("MoveGroupFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UnGroup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnGroup {
            get {
                return ResourceManager.GetString("UnGroup", resourceCulture);
            }
        }
    }
}
